export const genres = [
    'memoir/autobiography',
    'nonfiction',
    'historical fiction',
    'fantasy',
    'science fiction',
    'dystopian',
    'action',
    'adventure',
    'mystery',
    'horror',
    'thriller',
    'romance',
    'poetry',
    'lgbtq+',
    'microrealism',
    'young adult',
    'new adult',
    'biography',
    'art',
    'history',
    'travel',
    'true crime',
    'children',
    'classics',
    'comics',
    'short',
    'philosophy',
];
